image: conanio/gcc8

stages:
  - build
  - test

build:
  stage: build
  script:
   - mkdir build && cd build
   - cmake -DCMAKE_BUILD_TYPE=Release ..
   - cmake --build .
  artifacts:
    paths:
     - build/bf

test:
  stage: test
  script:
   - build/bf test-simple
